export * from "./a.ts";
export * from "./aaaa.ts";
export * from "./cname.ts";
export * from "./mx.ts";
export * from "./ns.ts";
export * from "./soa.ts";
export * from "./srv.ts";
export * from "./txt.ts";
export * from "./types.ts";
