name: Run Tests
on: [push, pull_request]
jobs:
  test:
    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x
    - run: |
        deno test --unstable --allow-net test.ts